### ISSUE TITLE
Incomplete implementation of JCKES SecretEntry

### ISSUE THREAD

**Issue by masonbedard** [doublereedkurt/pyjks#9]
In jks.py, there is a TODO for handling SecretKey entries, which are a type in JCKES but not JKS. That is exactly the functionality I need, so I was looking through the JceKeyStore implementation on grepcode but saw that the sealed object part of a secret entry is a serialized object that Java loads by using an ObjectInputStream. For the PrivateKey and Cert entries, it looks like the number of bytes for each part of the entry is specified in some way either by the type or by a length property.

I'd be happy to write the code if anyone might be able to tell me if it's possible to read the serialized object (of unknown size I think) byte by byte, and then unserialize it. I'm very much a novice with regards to JKS and JCKES, so I'm sorry if this is a nonissue.

**Comment by voetsjoeba** [comment]
Implemented in pull request #10

**Comment by doublereedkurt** [comment]
I'm going to close this issue for now please feel free to re-open if PR did not fix it.

Thanks voetsjoeba for the new feature!
